[package]
name = "kcs_decoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riff-wave = "0.1.3"
clap = { version = "4.2.7", features = ["derive"] }
